name: flutter_notebook_chapter_39
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  gap: ^3.0.1
  hugeicons: ^0.0.7
  go_router: ^14.2.7
  dio: ^5.7.0
  genq:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
